# Uncomment the next line to define a global platform for your project
# platform :ios

target 'MoodGrid' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MoodGrid

pod 'Firebase/Core'
pod 'Firebase/Auth'

pod 'Alamofire', '~> 4.7'
pod 'SwiftyJSON', '~> 4.0'

end
